pipeline {
    agent any

    stages {
        stage('Install dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest sources/test_calc.py'
            }
        }

        stage('Build Executable') {
            steps {
                // Using --no-lsb as a workaround to avoid Python shared lib error
                sh 'pyinstaller --onefile --no-lsb sources/add2vals.py'
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'dist/add2vals*', fingerprint: true
            }
        }
    }
}

