pipeline {
    agent any

    stages {
        stage('Install dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest tests/test_calc.py'
            }
        }

        stage('Build Executable') {
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'dist/add2vals*', fingerprint: true
            }
        }
    }
}

