pipeline {
    agent any

    environment {
        VENV_DIR = 'venv310'
        PYTHON = './venv310/bin/python3.10'
        PIP = './venv310/bin/pip'
        PYTEST = './venv310/bin/pytest'
        PYINSTALLER = './venv310/bin/pyinstaller'
    }

    stages {
        stage('Set up Python 3.10 venv') {
            steps {
                sh '''
                    python3.10 -m venv ${VENV_DIR}
                    ${PIP} install --upgrade pip
                '''
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    ${PIP} install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    ${PYTEST} sources/test_calc.py
                '''
            }
        }

        stage('Build Executable') {
            steps {
                sh '''
                    ${PYINSTALLER} --onefile sources/add2vals.py
                '''
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'dist/add2vals*', fingerprint: true
            }
        }
    }
}

